### PR TITLE
return rating metadata even if there are no ratings for the spec

### PR DESCRIPTION
**Pull request by adamkorynta**

### CODE REVIEW

**Comment by rma-rripken** [comment]
Is this related to a 13b issue?

**Comment by adamkorynta** [comment]
Trying to get my task 1a tests passing. I didn't create an issue for this.

**Comment by rma-rripken** [comment]
This removes the join with virtual and transitional ratings.  Not saying that those worked perfectly but I was hoping we'd build that out not remove it

**Review by rma-rripken — APPROVED** [review]

**Comment by rma-rripken** [comment]
I missed that this switches to av_rating_spec view.  Hopefully that makes the joins I was complaining about unnecessary.

**Comment by MikeNeilson** [comment]
That is worth verifying. I suggest opening an issue with a little more detail about exactly what needs to be tested there.

**Pull request merged**
