### PR TITLE
Added bounding-office regex to Timeseries catalog.

### LINKED ISSUE #437: Bounding office for timeseries catalog
It would be good to search for time series by bounding office.

I suspect the solution is either an additional "limit query"/"with clause" or minor mods to the existing one that already does some searching by location; just not sure if the bounding office is exposed correctly to that query.

### PR DESCRIPTION
**Pull request by rma-rripken**
#427

### CODE REVIEW

**Comment by rma-rripken** [comment]
I couldn't find a bounding office on AV_CWMS_TS_ID2 so if that condition is added I have to join with AV_LOC2

**Comment by MikeNeilson** [comment]
A reasonable choice though that av_loc2 view concerns me. Any immediate adverse impact on performance? Considering it's two columns it should be minimal but I verified yesterday that that's the view that killing most performance on the location catalog.

**Comment by rma-rripken** [comment]
I made it so the join only happens if the bounding_office parameter is provided.  I haven't done any performance tests - my database just doesn't have a significant amount of data.

**Comment by MikeNeilson** [comment]
Fair. If is is an issue it'll need to be worked on separately anyways, I suspect.

**Review by MikeNeilson — DISMISSED** [review]

**Review by MikeNeilson — APPROVED** [review]

**Pull request merged**
