### PR TITLE
add error code 404 handling on the location controller

### PR DESCRIPTION
**Pull request by adamkorynta**

### CODE REVIEW

**Review by MikeNeilson — APPROVED** [review]

**Comment by rma-rripken** [comment]
I know this already got merged but something isn't right - there should have already been a catch in ApiServlet for NotFoundException.  Its a fairly common thing.

**Comment by rma-rripken** [comment]
Hmm,  @MikeNeilson change 990c189649f6ba3e2ce4e21f24730ea1145ddad7  removed NotFoundException handling from ApiServlet.  Was that intentional?

**Comment by adamkorynta** [comment]
I copied the catch from the TimeSeriesController and assumed that was the right way to handle it

**Comment by rma-rripken** [comment]
Not saying its wrong to catch and handle it in the controller.  Its just wrong that you HAVE to.  For NotFound it should have been optional

**Comment by adamkorynta** [comment]
I'm certainly in favor of a global handling in ApiServlet

**Comment by MikeNeilson** [comment]
Ryan is right, I'm even the one that setup that system and totally forgot.

**Comment by MikeNeilson** [comment]
> Hmm, @MikeNeilson change [990c189](https://github.com/USACE/cwms-radar-api/commit/990c189649f6ba3e2ce4e21f24730ea1145ddad7) removed NotFoundException handling from ApiServlet. Was that intentional?

No, that probably happened in one of my botched rebases (always forgetting to continue the rebase before I start working again.)

**Pull request merged**
