### PR TITLE
Changes to read directly from user provided stream and avoid "Payload…

### PR DESCRIPTION
**Pull request by rma-rripken**
… Too Large"

### CODE REVIEW

**Comment by rma-rripken** [comment]
This is for #632.  
Ideally I'd also add a unit test with an input that exceeds 2MB.   At the moment that seems tedious to create.  I think its just the size of the body that gets POST'd that needs to be big so it probably could be programmatically generated.   Maybe try to do a create with points for 20 years?  I could use a suggestion on the easiest test that demonstrated the old limits

**Comment by MikeNeilson** [comment]
> This is for #632. Ideally I'd also add a unit test with an input that exceeds 2MB. At the moment that seems tedious to create. I think its just the size of the body that gets POST'd that needs to be big so it probably could be programmatically generated. Maybe try to do a create with points for 20 years? I could use a suggestion on the easiest test that demonstrated the old limits

@msweier Got a lot of data to provide us so Ryan can run this test?

**Review by MikeNeilson — COMMENTED** [review]
Looks good. Let's given Mitch some time to see if he can build that bulk test set for us.

**Comment by rma-rripken** [comment]
I hacked together a test that makes a big input.

**Review by MikeNeilson — APPROVED** [review]
Nice trick.

**Comment by msweier** [comment]
Some of our longer period of record TS are about 13 MB or so, but most of that is from the 9 years of 15 minute data.

**Comment by MikeNeilson** [comment]
> Some of our longer period of record TS are about 13 MB or so, but most of that is from the 9 years of 15 minute data.

I think I'd be more worried about CWMS DB being able to save that in a reasonable amount of time than CDA doing the initial processing.

But that'll be a good request to use in some future load testing. I doubt you'd do it often but it could definitely interfere with other real-time ops if done so we should test that.

**Comment by msweier** [comment]
> I think I'd be more worried about CWMS DB being able to save that in a reasonable amount of time than CDA doing the initial processing.

I agree. It takes about 8 minutes to save to a district instance for 13 MB in a loop that breaks it up into 2 MB chunks. It's long but not terrible since it's more of a one off deal. I didn't try CWBI test.

**Comment by rma-rripken** [comment]
I made a test and validated that it failed without these changes so I don't need more in the short term.  These changes won't make the saves happen any faster.  There still might be reasons you want to break bigger timeseries into smaller chunks.   13MB shouldn't cause the size problem you were seeing before.  It will probably still take the same amount of time in total.

**Pull request merged**
