### PR TITLE
Adding a test to verify parsing of the timestamp example used in Time…

### PR DESCRIPTION
**Pull request by rma-rripken**
…seriesController and basically every Controller.

### CODE REVIEW

**Comment by rma-rripken** [comment]
@krowvin What examples are failing to parse?  

I did some grepping of the code and as far as I can tell:
Every Instant parsed in a Controller goes thru one of:
Controllers.requiredInstant which goes thru queryParamAsZdt
Or queryParamAsInstant which goes thru queryParamAsZdt
Or DateUtil.parseUserDate(...).toIInstant()

Every ZonedDateTime in a Controller goes thru:
Controllers.requiredZdt which calls queryParamAsZdt
or queryParamAsZdt which calls DateUtils.parseUserDate
or DateUtils.parseUserDate

**Comment by MikeNeilson** [comment]
The example provided in the swagger ui was something that didn't validate.

**Comment by krowvin** [comment]
> The example provided in the swagger ui was something that didn't validate.  

Yes, this

But also in the swagger UI there are date fields that do not provide an expected format. In the example Value it just lists the primitive `string`. 

EDIT: Example is the Levels endpoint here (older version) https://cwms-data.usace.army.mil/cwms-data/swagger-ui.html
image

For example the levels endpoint takes an effective-date. Without telling users explicitly what date to type in; it leaves them to enter a variety of dates until they get it. 

Nevermind the other level issues that exist existed prior to recent changes/database fixes/data. 

And maybe it's just that one date field! I tried to think of a clever way to search for all the various annotations, but gave up.

**Comment by rma-rripken** [comment]
Ok.  Mike's quote is that it "was" something - not that it still is?  Right?  As far as I can see the date parsing is currently fine and the documentation example is fine.   This was brought up under the "issues" agenda item so I want to be clear whether its currently an issue or maybe its just an issue for older CDA sites?

With regard to a good example not being provided in Swagger-ui and just seeing "string" - I don't think we are able to change that with the javalin version we currently have to use.  Which is one reason we started putting examples in the field descriptions.

In this issue I suggested we create a timestamp documentation page and link to it from every timestamp type end-point. Similar to how we've handled regex fields.  My questions and suggestion got no response and the issue is still tagged needs-approval
https://github.com/USACE/cwms-data-api/issues/570



> Nevermind the other level issues that exist existed prior to recent changes/database fixes/data. 

I'm not sure what is meant by this - if you know of level issues I hope you report, create issues and track them.

**Comment by krowvin** [comment]
>  I hope you report  

The issues are known and the latest release will fix it

As for the tests I will close this issue as it appears you were testing CDA's internal handling of the datetimes and not just presentation on swagger pages. 

An additional docs page on datetimes and the formats that can be pointed to would certainly solve this. And perhaps anywhere a date is set for input in the swagger page we can reference the new doc. [docs here]etc

**Review by krowvin — APPROVED** [review]
Looks good. just doing a spot check of the dates to confirm the generated date matches the expected.

**Pull request merged**
